name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Generate Pac-Man Graph (Light)
        uses: Platane/snk@v3
        with:
          github_user_name: "ahmedtarek-mel"
          outputs: |
            pacman-contribution-graph.svg

      - name: Generate Pac-Man Graph (Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: "ahmedtarek-mel"
          color_snake: "#00FF00"
          outputs: |
            pacman-contribution-graph-dark.svg

      - name: Upload generated files to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: "."
          keep_files: true
