name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pac-Man Graph (Light)
        uses: Platane/snk@v3
        with:
          github_user_name: ahmedtarek-mel
          outputs: |
            pacman-contribution-graph.svg

      - name: Generate Pac-Man Graph (Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: ahmedtarek-mel
          outputs: |
            pacman-contribution-graph-dark.svg

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
