name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Pac-Man Graph
        uses: yoshi389111/github-contribution-grid-snake@main
        with:
          github_user_name: "ahmedtarek-mel"
          svg_out_path: "pacman-contribution-graph.svg"
          snake_color: "#00FFFF"

      - name: Generate Pac-Man Graph (Dark)
        uses: yoshi389111/github-contribution-grid-snake@main
        with:
          github_user_name: "ahmedtarek-mel"
          svg_out_path: "pacman-contribution-graph-dark.svg"
          snake_color: "#FF0000"

      - name: Publish to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
